import { AnalysisResult, LogicalIntegrityAnalysis, ModelCouncilResponse, PastSelfDebateResult } from '../types';

export interface ExportToDocsPayload {
  title?: string;
  originalText?: string;
  analysis?: AnalysisResult | null;
  integrityAnalysis?: LogicalIntegrityAnalysis | null;
  councilResponse?: ModelCouncilResponse | null;
  pastSelfDebate?: PastSelfDebateResult | null;
}

export async function exportToGoogleDoc(
  accessToken: string,
  payload: ExportToDocsPayload
): Promise<{ fileId: string; documentUrl: string; title: string }> {
  const docTitle = payload.title || `Argument Map Analysis - ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;
  
  // Construct clean HTML report for native Google Doc formatting conversion
  let html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: 'Arial', sans-serif; color: #1e293b; line-height: 1.6; margin: 20px; }
          h1 { color: #312e81; border-bottom: 2px solid #6366f1; padding-bottom: 8px; font-size: 24pt; }
          h2 { color: #4338ca; margin-top: 24px; font-size: 16pt; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
          h3 { color: #1e1b4b; font-size: 13pt; margin-top: 16px; }
          .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 9pt; font-weight: bold; }
          .badge-strong { background-color: #d1fae5; color: #065f46; }
          .badge-loop { background-color: #fef3c7; color: #92400e; }
          .badge-deadend { background-color: #ffe4e6; color: #9f1239; }
          .badge-high { background-color: #fecdd3; color: #881337; }
          .badge-med { background-color: #fed7aa; color: #7c2d12; }
          .quote-box { background-color: #f8fafc; border-left: 4px solid #6366f1; padding: 12px 16px; margin: 12px 0; font-style: italic; }
          .card { background-color: #f1f5f9; border: 1px solid #cbd5e1; border-radius: 8px; padding: 12px 16px; margin-bottom: 12px; }
          .critique-item { background-color: #fff1f2; border-left: 4px solid #f43f5e; padding: 10px 14px; margin: 8px 0; }
          table { width: 100%; border-collapse: collapse; margin-top: 12px; }
          th, td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; font-size: 10pt; }
          th { background-color: #e2e8f0; color: #1e293b; font-weight: bold; }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(docTitle)}</h1>
        <p><em>Generated by Argument Transit Map • ${new Date().toLocaleString()}</em></p>
  `;

  // Original Text
  if (payload.originalText) {
    html += `
      <h2>1. Source Draft Text</h2>
      <div class="quote-box">"${escapeHtml(payload.originalText)}"</div>
    `;
  }

  // Analysis Transit Map Nodes
  if (payload.analysis && payload.analysis.stations.length > 0) {
    html += `
      <h2>2. Argument Line Topology (${payload.analysis.stations.length} Station Nodes)</h2>
      <p>The structured breakdown of logical premises, loops, and dead-end conclusions in your draft:</p>
      <table>
        <thead>
          <tr>
            <th style="width: 5%;">#</th>
            <th style="width: 25%;">Station Label</th>
            <th style="width: 50%;">Summary / Argument Premise</th>
            <th style="width: 20%;">Type & Sentiment</th>
          </tr>
        </thead>
        <tbody>
    `;

    payload.analysis.stations.forEach((stn, idx) => {
      const typeLabel = stn.type === 'STRONG_LINK' ? 'Strong Link' : stn.type === 'LOOP' ? `Logical Loop (to #${stn.loopsTo || '?'})` : 'Dead End';
      const badgeClass = stn.type === 'STRONG_LINK' ? 'badge-strong' : stn.type === 'LOOP' ? 'badge-loop' : 'badge-deadend';
      const isInterchange = payload.analysis?.interchanges.includes(stn.id);

      html += `
        <tr>
          <td><strong>${idx + 1}</strong></td>
          <td>
            <strong>${escapeHtml(stn.label)}</strong>
            ${isInterchange ? ' <span class="badge" style="background-color:#e0e7ff; color:#3730a3;">Interchange</span>' : ''}
          </td>
          <td>${escapeHtml(stn.summary)}</td>
          <td><span class="badge ${badgeClass}">${typeLabel}</span></td>
        </tr>
      `;
    });

    html += `
        </tbody>
      </table>
    `;

    // Blunt Critiques
    if (payload.analysis.critiques && payload.analysis.critiques.length > 0) {
      html += `
        <h3>Structural Critiques & Friction Points</h3>
        <ul>
      `;
      payload.analysis.critiques.forEach((c) => {
        html += `<li style="margin-bottom: 6px;">${escapeHtml(c)}</li>`;
      });
      html += `</ul>`;
    }
  }

  // Logical Integrity Analysis
  if (payload.integrityAnalysis) {
    html += `
      <h2>3. Logical Integrity Audit</h2>
      <p><strong>Overall Argument Integrity Score:</strong> <span style="font-size: 16pt; font-weight: bold; color: ${payload.integrityAnalysis.overallScore >= 75 ? '#059669' : payload.integrityAnalysis.overallScore >= 50 ? '#d97706' : '#dc2626'}">${payload.integrityAnalysis.overallScore}/100</span></p>
      <p><em>${escapeHtml(payload.integrityAnalysis.summary)}</em></p>
    `;

    if (payload.integrityAnalysis.issues.length > 0) {
      html += `
        <h3>Identified Vulnerabilities & Fallacies (${payload.integrityAnalysis.issues.length})</h3>
      `;
      payload.integrityAnalysis.issues.forEach((issue) => {
        const severityClass = issue.severity === 'HIGH' ? 'badge-high' : 'badge-med';
        html += `
          <div class="card">
            <p style="margin: 0 0 4px 0;">
              <span class="badge ${severityClass}">${issue.severity} SEVERITY</span>
              <strong>${escapeHtml(issue.title)}</strong> (${escapeHtml(issue.type)})
            </p>
            <p style="margin: 4px 0;"><strong>Vulnerability:</strong> ${escapeHtml(issue.explanation)}</p>
            <p style="margin: 4px 0; color: #4338ca;"><strong>Actionable Repair:</strong> ${escapeHtml(issue.suggestedFix)}</p>
          </div>
        `;
      });
    }
  }

  // Model Council Perspectives
  if (payload.councilResponse && payload.councilResponse.personaResults.length > 0) {
    html += `
      <h2>4. Model Council Peer Review</h2>
      <p>Cross-perspective critiques from specialized evaluators:</p>
    `;

    payload.councilResponse.personaResults.forEach((res) => {
      html += `
        <div class="card">
          <p style="margin: 0 0 4px 0; font-size: 12pt;">
            <strong>${escapeHtml(res.personaName)}</strong> — <em>${escapeHtml(res.personaRole)}</em>
            <span style="float: right; font-weight: bold; color: #4338ca;">Approval: ${res.approvalRating}%</span>
          </p>
          <p style="margin: 4px 0;"><strong>Verdict:</strong> ${escapeHtml(res.overallVerdict)}</p>
      `;

      if (res.critiques && res.critiques.length > 0) {
        html += `<ul style="margin-top: 6px;">`;
        res.critiques.forEach((crit) => {
          html += `
            <li style="margin-bottom: 4px;">
              <strong>[${escapeHtml(crit.aspect)}]</strong> ${escapeHtml(crit.concern)}
              <br><span style="color: #047857;">💡 Recommendation: ${escapeHtml(crit.recommendation)}</span>
            </li>
          `;
        });
        html += `</ul>`;
      }

      html += `</div>`;
    });
  }

  // Past Self Debate
  if (payload.pastSelfDebate) {
    html += `
      <h2>5. Dialectical Self-Debate Log</h2>
      <p><strong>Perspective Persona:</strong> ${escapeHtml(payload.pastSelfDebate.personaName)} (${escapeHtml(payload.pastSelfDebate.personaEra)})</p>
      <div class="quote-box">
        <strong>Core Contradiction:</strong> ${escapeHtml(payload.pastSelfDebate.coreContradiction)}
      </div>
    `;

    if (payload.pastSelfDebate.exchanges.length > 0) {
      payload.pastSelfDebate.exchanges.forEach((ex, idx) => {
        html += `
          <div class="card">
            <p style="margin: 0 0 4px 0;"><strong>Exchange #${idx + 1}: ${escapeHtml(ex.challengeType)}</strong></p>
            <p><strong>Past Self Quote:</strong> "${escapeHtml(ex.pastSelfQuote)}"</p>
            <p><strong>Current Draft Claim:</strong> "${escapeHtml(ex.currentClaim)}"</p>
            <p style="color: #9f1239;"><strong>Past Self Challenge:</strong> ${escapeHtml(ex.pastSelfQuestion)}</p>
            ${ex.userDefense ? `<p style="color: #047857;"><strong>Author Defense:</strong> "${escapeHtml(ex.userDefense)}"</p>` : ''}
            ${ex.pastSelfRebuttal ? `<p style="color: #4338ca;"><strong>Past Self Counter:</strong> ${escapeHtml(ex.pastSelfRebuttal)}</p>` : ''}
          </div>
        `;
      });
    }
  }

  html += `
      </body>
    </html>
  `;

  // Multipart Drive API Upload
  const metadata = {
    name: docTitle,
    mimeType: 'application/vnd.google-apps.document',
  };

  const boundary = 'argument_transit_map_boundary';
  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelim = `\r\n--${boundary}--`;

  const multipartRequestBody =
    delimiter +
    'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
    JSON.stringify(metadata) +
    delimiter +
    'Content-Type: text/html; charset=UTF-8\r\n\r\n' +
    html +
    closeDelim;

  const res = await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': `multipart/related; boundary=${boundary}`,
    },
    body: multipartRequestBody,
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Google Drive API error (${res.status}): ${errText}`);
  }

  const data = await res.json();
  const fileId = data.id;
  const documentUrl = `https://docs.google.com/document/d/${fileId}/edit`;

  return {
    fileId,
    documentUrl,
    title: docTitle,
  };
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
